modLoader="javafml"

loaderVersion="[40,)"
license="https://github.com/florian-berger/simple-recipes/blob/master/LICENSE"
issueTrackerURL="https://github.com/florian-berger/simple-recipes/issues"

[[mods]]
modId="ultissimplerecipes"
version="${file.jarVersion}"
displayName="Ulti's Simple Recipes"
logoFile="ultis-simple-recipes.png"

displayURL="https://berger-media.biz/downloads/12/minecraft/ultis-simple-recipes"
authors="Florian <UltimateG4ming> Berger"

description='''
This mod is adding some recipes to make the crafting processes in the game less complex. For example, you don't need to convert logs to planks for making sticks or chests.
'''

[[dependencies.ultissimplerecipes]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ultissimplerecipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
